### ISSUE TITLE
I am having problems to use the tool (A STRANGE ERROR OCCURRED)

### ISSUE THREAD

**Issue by EscrVirtuoso** [The-Ethical-Guy/Evora#3]
Hello The-Ethical-Guy,

I'm having some problems with the tool, whether it is running on cli or in web interface. To be honest, I can't even use it, because everytime I'm using it I just have the message "A STRANGE ERROR OCCURRED, PLEASE RESTART THE TOOL".

I tried to uninstall and reinstall but nothing is helping, that's why I'm sending you this message.

If you have any idea or maybe something I didn't do to setup the tool, it would be very appreciated.

Thank you very much in advance for your help :)

**Comment by The-Ethical-Guy** [comment]
that's mean u have problem in the internet communication or with the OS dependencies so please share more information of or OS and it's version and try to use the tool in vm and if it didn't work then u need to fix the networking issues try to close check ip tables and ur waf

**Comment by JUSTICE2129** [comment]
im having same issue

**Comment by EscrVirtuoso** [comment]
Yeah I tried to uninstall and reinstall the tool, I used it while being a normal user or as root and nothing is working.

I'm using Kali Linux, everything is up to date, I also did "pip install -r requirements.txt" to be sure that everything is installed but well I have absolutely no idea what is causing problems. 

Is there some setup steps I didn't see ? I think I'm not the only one to have those problems to be honest.

Thank you very much for your tool anyway, it is a good idea to develop it :)

**Comment by The-Ethical-Guy** [comment]
> Yeah I tried to uninstall and reinstall the tool, I used it while being a normal user or as root and nothing is working.
> 
> I'm using Kali Linux, everything is up to date, I also did "pip install -r requirements.txt" to be sure that everything is installed but well I have absolutely no idea what is causing problems.
> 
> Is there some setup steps I didn't see ? I think I'm not the only one to have those problems to be honest.
> 
> Thank you very much for your tool anyway, it is a good idea to develop it :)

first i added some new features to the installer, now the tool is using venv to work so try to install it again

second this problem isn't directly in the tool, this problem in the network api communication for some reason the api isn't working well with u, so we can try some debugging techniques to find the problem can u give me ur email?
