### ISSUE TITLE
SyntaxError: Non-UTF-8 code

### ISSUE THREAD

**Issue by 4ggggggg** [The-Ethical-Guy/Evora#4]
evora -w 80
SyntaxError: Non-UTF-8 code starting with '\xa7' in file /home/hc/Evora/evora-web.py on line 1, but no encoding declared; see https://peps.python.org/pep-0263/ for details

**Comment by chill-c0der2** [comment]
same issue

**Comment by The-Ethical-Guy** [comment]
just use an older version of python like 3.11 :)

**Comment by The-Ethical-Guy** [comment]
i modified the launcher to use python3.11 and now it's working fine
