### ISSUE TITLE
Problem using the tool

### ISSUE THREAD

**Issue by AhmedYasser1-9** [The-Ethical-Guy/Evora#5]
The problem is in the readline that is needed to install I tried to install it by 
pip install readline==6.2
pip install --only-binary=:all: readline
but they failed

I followed the steps correctly 'till I reached evora -h and it worked then I tried evora -t it gave me an error due to missing request module or something in python anyways to fix this I must make this : 
pip install -r /home/kali/Evora/requirements.txt
and then It faces the problem of readline

![image](https://github.com/user-attachments/assets/b0328a4b-c856-4b04-b2a1-34d2e6d112a7)
![image](https://github.com/user-attachments/assets/8465ac86-6960-448d-a4bc-1a60325b8a67)

**Desktop (please complete the following information):**
 - OS: kali linux

**Comment by The-Ethical-Guy** [comment]
the main problem that you don't have python 3.11 and this is why the tool is not working, its only compatible with v3.11 and the lower versions
